import "./globals.css";
import FirebaseTest from "./FirebaseTest";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <FirebaseTest app={children} />
      </body>
    </html>
  );
}
